[package]
name = "rombok"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rombok_macro={ version="0.1.0", path="../rombok_macro" }
